# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOMAIN: ${{ secrets.DOMAIN }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  ANDROID_DEVICE: 'Nexus 6'
  ANDROID_IMAGE: 'system-images;android-29;google_apis;x86_64'
  DEVICE_NAME: 'nexus_6'
  PLATFORM_VERSION: '10.0'
  BROWSER_NAME: 'chrome'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Clean Packages
        run: |
          rm -rf node_modules
          npm cache clean --force
          rm -rf package-lock.json

      - name: Install Appium
        run: npm install -g appium --chromedriver_version="74.0.3729.6"

      - name: Install Android Emulator and Create Android Virtual Device
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install '${{ env.ANDROID_IMAGE }}'
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n ${{ env.DEVICE_NAME }} -k '${{ env.ANDROID_IMAGE }}' --force --device "${{ env.ANDROID_DEVICE }}"
          echo "---- List emulator:"
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Start emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd ${{ env.DEVICE_NAME }} -no-snapshot > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          echo "---- Emulator started:"
          $ANDROID_HOME/platform-tools/adb devices

      - name: Install dependencies
        run: npm install

      - name: Run test script
        id: testkuc
        run: npm run test
        continue-on-error: true

      - name: Upload wdio-appium log
        uses: actions/upload-artifact@v1
        with:
          name: wdio-appium.log
          path: wdio-appium.log

      - name: Upload image result
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: .tmp

      - name: Check on failures
        if: (${{ success() }} || ${{ failure() }}) && (${{ steps.testkuc.outcome }} == 'failure')
        run: exit 1